import type { TranslationKey } from '@/i18n/translations';

export type BacktestRunDetailsCopy = {
  loadingTitle: string;
  loadErrorTitle: string;
  loadErrorDefault: string;
  retry: string;
  notFoundTitle: string;
  notFoundDescription: string;
  statusInProgress: string;
  statusCompleted: string;
  statusRunning: string;
  statusPending: string;
  statusFailed: string;
  statusCanceled: string;
  runPreview: string;
  marketGroup: string;
  strategy: string;
  calcStart: string;
  calcEnd: string;
  progressTitle: string;
  stageRunCreated: string;
  stageEngineRunning: string;
  stageTradesReady: string;
  stageReportReady: string;
  stageRunFinished: string;
  trades: string;
  netPnl: string;
  winRate: string;
  maxDrawdown: string;
  stagesTitle: string;
  tabSummary: string;
  tabMarkets: string;
  tabTrades: string;
  tabRaw: string;
  reportNotReadyTitle: string;
  reportNotReadyDescription: string;
  summaryNetPnl: string;
  summaryWinRate: string;
  summaryTrades: string;
  summaryMaxDrawdown: string;
  summaryStartBalance: string;
  summaryEndBalance: string;
  summaryDailyPnlTitle: string;
  summaryBalanceTitle: string;
  summaryDailyPnlNoData: string;
  summaryBalanceNoData: string;
  marketsEmptyTitle: string;
  marketsEmptyDescription: string;
  globalLegendTitle: string;
  legendEntryLong: string;
  legendEntryShort: string;
  legendExitProfit: string;
  legendExitLoss: string;
  legendDca: string;
  timelineLoading: string;
  timelineLoadingPhaseEvents: string;
  timelineLoadingPhaseCandles: string;
  timelineLoadingPrefix: string;
  timelineNoCandles: string;
  timelineLoadErrorDefault: string;
  timelineParityFailedDefault: string;
  zoom: string;
  zoomOutTitle: string;
  zoomInTitle: string;
  pairStatsTitle: string;
  parityFailed: string;
  runTotalValue: string;
  chartWindowValue: string;
  avgHold: string;
  pnl: string;
  dca: string;
  executionTitle: string;
  avgEntry: string;
  avgExit: string;
  closedOnLastCandle: string;
  liquidations: string;
  dataRangeTitle: string;
  tradesRange: string;
  candlesRange: string;
  chartMinMax: string;
  indicatorsTitle: string;
  noIndicators: string;
  noTradesTitle: string;
  noTradesDescription: string;
  totalProfit: string;
  totalLoss: string;
  extremes: string;
  biggestWin: string;
  biggestLoss: string;
  colSymbol: string;
  colSide: string;
  colOpen: string;
  colClose: string;
  colDuration: string;
  colQty: string;
  colDca: string;
  colEntry: string;
  colExit: string;
  colNotionalEntry: string;
  colNotionalExit: string;
  colMarginEntry: string;
  colMarginExit: string;
  colMoveSide: string;
  colPnlNotional: string;
  colPnlMargin: string;
  colFee: string;
  colExitReason: string;
  exitReasonSignal: string;
  exitReasonFinalCandle: string;
  exitReasonLiquidation: string;
  colPnl: string;
  colCumPnl: string;
  dash: string;
  custom: string;
};

const DETAIL_KEYS = {
  loadingTitle: 'dashboard.backtests.details.loadingTitle',
  loadErrorTitle: 'dashboard.backtests.details.loadErrorTitle',
  loadErrorDefault: 'dashboard.backtests.details.loadErrorDefault',
  retry: 'dashboard.backtests.details.retry',
  notFoundTitle: 'dashboard.backtests.details.notFoundTitle',
  notFoundDescription: 'dashboard.backtests.details.notFoundDescription',
  statusInProgress: 'dashboard.backtests.details.statusInProgress',
  statusCompleted: 'dashboard.backtests.details.statusCompleted',
  statusRunning: 'dashboard.backtests.details.statusRunning',
  statusPending: 'dashboard.backtests.details.statusPending',
  statusFailed: 'dashboard.backtests.details.statusFailed',
  statusCanceled: 'dashboard.backtests.details.statusCanceled',
  runPreview: 'dashboard.backtests.details.runPreview',
  marketGroup: 'dashboard.backtests.details.marketGroup',
  strategy: 'dashboard.backtests.details.strategy',
  calcStart: 'dashboard.backtests.details.calcStart',
  calcEnd: 'dashboard.backtests.details.calcEnd',
  progressTitle: 'dashboard.backtests.details.progressTitle',
  stageRunCreated: 'dashboard.backtests.details.stageRunCreated',
  stageEngineRunning: 'dashboard.backtests.details.stageEngineRunning',
  stageTradesReady: 'dashboard.backtests.details.stageTradesReady',
  stageReportReady: 'dashboard.backtests.details.stageReportReady',
  stageRunFinished: 'dashboard.backtests.details.stageRunFinished',
  trades: 'dashboard.backtests.details.trades',
  netPnl: 'dashboard.backtests.details.netPnl',
  winRate: 'dashboard.backtests.details.winRate',
  maxDrawdown: 'dashboard.backtests.details.maxDrawdown',
  stagesTitle: 'dashboard.backtests.details.stagesTitle',
  tabSummary: 'dashboard.backtests.details.tabSummary',
  tabMarkets: 'dashboard.backtests.details.tabMarkets',
  tabTrades: 'dashboard.backtests.details.tabTrades',
  tabRaw: 'dashboard.backtests.details.tabRaw',
  reportNotReadyTitle: 'dashboard.backtests.details.reportNotReadyTitle',
  reportNotReadyDescription: 'dashboard.backtests.details.reportNotReadyDescription',
  summaryNetPnl: 'dashboard.backtests.details.summaryNetPnl',
  summaryWinRate: 'dashboard.backtests.details.summaryWinRate',
  summaryTrades: 'dashboard.backtests.details.summaryTrades',
  summaryMaxDrawdown: 'dashboard.backtests.details.summaryMaxDrawdown',
  summaryStartBalance: 'dashboard.backtests.details.summaryStartBalance',
  summaryEndBalance: 'dashboard.backtests.details.summaryEndBalance',
  summaryDailyPnlTitle: 'dashboard.backtests.details.summaryDailyPnlTitle',
  summaryBalanceTitle: 'dashboard.backtests.details.summaryBalanceTitle',
  summaryDailyPnlNoData: 'dashboard.backtests.details.summaryDailyPnlNoData',
  summaryBalanceNoData: 'dashboard.backtests.details.summaryBalanceNoData',
  marketsEmptyTitle: 'dashboard.backtests.details.marketsEmptyTitle',
  marketsEmptyDescription: 'dashboard.backtests.details.marketsEmptyDescription',
  globalLegendTitle: 'dashboard.backtests.details.globalLegendTitle',
  legendEntryLong: 'dashboard.backtests.details.legendEntryLong',
  legendEntryShort: 'dashboard.backtests.details.legendEntryShort',
  legendExitProfit: 'dashboard.backtests.details.legendExitProfit',
  legendExitLoss: 'dashboard.backtests.details.legendExitLoss',
  legendDca: 'dashboard.backtests.details.legendDca',
  timelineLoading: 'dashboard.backtests.details.timelineLoading',
  timelineLoadingPhaseEvents: 'dashboard.backtests.details.timelineLoadingPhaseEvents',
  timelineLoadingPhaseCandles: 'dashboard.backtests.details.timelineLoadingPhaseCandles',
  timelineLoadingPrefix: 'dashboard.backtests.details.timelineLoadingPrefix',
  timelineNoCandles: 'dashboard.backtests.details.timelineNoCandles',
  timelineLoadErrorDefault: 'dashboard.backtests.details.timelineLoadErrorDefault',
  timelineParityFailedDefault: 'dashboard.backtests.details.timelineParityFailedDefault',
  zoom: 'dashboard.backtests.details.zoom',
  zoomOutTitle: 'dashboard.backtests.details.zoomOutTitle',
  zoomInTitle: 'dashboard.backtests.details.zoomInTitle',
  pairStatsTitle: 'dashboard.backtests.details.pairStatsTitle',
  parityFailed: 'dashboard.backtests.details.parityFailed',
  runTotalValue: 'dashboard.backtests.details.runTotalValue',
  chartWindowValue: 'dashboard.backtests.details.chartWindowValue',
  avgHold: 'dashboard.backtests.details.avgHold',
  pnl: 'dashboard.backtests.details.pnl',
  dca: 'dashboard.backtests.details.dca',
  executionTitle: 'dashboard.backtests.details.executionTitle',
  avgEntry: 'dashboard.backtests.details.avgEntry',
  avgExit: 'dashboard.backtests.details.avgExit',
  closedOnLastCandle: 'dashboard.backtests.details.closedOnLastCandle',
  liquidations: 'dashboard.backtests.details.liquidations',
  dataRangeTitle: 'dashboard.backtests.details.dataRangeTitle',
  tradesRange: 'dashboard.backtests.details.tradesRange',
  candlesRange: 'dashboard.backtests.details.candlesRange',
  chartMinMax: 'dashboard.backtests.details.chartMinMax',
  indicatorsTitle: 'dashboard.backtests.details.indicatorsTitle',
  noIndicators: 'dashboard.backtests.details.noIndicators',
  noTradesTitle: 'dashboard.backtests.details.noTradesTitle',
  noTradesDescription: 'dashboard.backtests.details.noTradesDescription',
  totalProfit: 'dashboard.backtests.details.totalProfit',
  totalLoss: 'dashboard.backtests.details.totalLoss',
  extremes: 'dashboard.backtests.details.extremes',
  biggestWin: 'dashboard.backtests.details.biggestWin',
  biggestLoss: 'dashboard.backtests.details.biggestLoss',
  colSymbol: 'dashboard.backtests.details.colSymbol',
  colSide: 'dashboard.backtests.details.colSide',
  colOpen: 'dashboard.backtests.details.colOpen',
  colClose: 'dashboard.backtests.details.colClose',
  colDuration: 'dashboard.backtests.details.colDuration',
  colQty: 'dashboard.backtests.details.colQty',
  colDca: 'dashboard.backtests.details.colDca',
  colEntry: 'dashboard.backtests.details.colEntry',
  colExit: 'dashboard.backtests.details.colExit',
  colNotionalEntry: 'dashboard.backtests.details.colNotionalEntry',
  colNotionalExit: 'dashboard.backtests.details.colNotionalExit',
  colMarginEntry: 'dashboard.backtests.details.colMarginEntry',
  colMarginExit: 'dashboard.backtests.details.colMarginExit',
  colMoveSide: 'dashboard.backtests.details.colMoveSide',
  colPnlNotional: 'dashboard.backtests.details.colPnlNotional',
  colPnlMargin: 'dashboard.backtests.details.colPnlMargin',
  colFee: 'dashboard.backtests.details.colFee',
  colExitReason: 'dashboard.backtests.details.colExitReason',
  exitReasonSignal: 'dashboard.backtests.details.exitReasonSignal',
  exitReasonFinalCandle: 'dashboard.backtests.details.exitReasonFinalCandle',
  exitReasonLiquidation: 'dashboard.backtests.details.exitReasonLiquidation',
  colPnl: 'dashboard.backtests.details.colPnl',
  colCumPnl: 'dashboard.backtests.details.colCumPnl',
  dash: 'dashboard.backtests.details.dash',
  custom: 'dashboard.backtests.details.custom',
} satisfies Record<keyof BacktestRunDetailsCopy, TranslationKey>;

export const getBacktestRunDetailsCopy = (
  t: (key: TranslationKey) => string,
): BacktestRunDetailsCopy =>
  Object.fromEntries(
    Object.entries(DETAIL_KEYS).map(([key, translationKey]) => [key, t(translationKey)]),
  ) as BacktestRunDetailsCopy;
